networks:
  dev-primeagfent:

services:
  primeagfent:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    image: dev-primeagfent
    container_name: dev-primeagfent
    restart: always
    ports:
      - "7860:7860"
      - "3000:3000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PRIMEAGFENT_DATABASE_URL=postgresql://primeagfent:primeagfent@postgres:5432/primeagfent
      - PRIMEAGFENT_SUPERUSER=primeagfent
      - PRIMEAGFENT_SUPERUSER_PASSWORD=primeagfent
      - PRIMEAGFENT_CONFIG_DIR=/var/lib/primeagfent
    env_file:
      - ../.env
    volumes:
      - ../:/app
    depends_on:
      - postgres
    networks:
      -  dev-primeagfent


  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: primeagfent
      POSTGRES_PASSWORD: primeagfent
      POSTGRES_DB: primeagfent
    ports:
      - "5432:5432"
    networks:
      -  dev-primeagfent

